export const headerNavLink = {
  display: "block",
  position: "relative",
  color: "#ffffff",
  textDecoration: "none",
  cursor: "pointer",
  margin: "2px 12px",
  "&:hover": {
    color: "# ffffff",
    "&::before": {
      transform: "scaleX(1)",
    },
  },
  "&::before": {
    content: '""',
    position: "absolute",
    display: "block",
    width: "100%",
    height: "2px",
    bottom: 0,
    left: 0,
    backgroundColor: " #ffffff",
    transform: "scaleX(0)",
    transition: "transform 0.3s ease",
  },
};

export const loginButton = {
  appearance: "none",
  backgroundColor: "transparent",
  border: "2px solid #ffffff",
  borderRadius: "20px",
  boxSizing: "border-box",
  color: "#ffffff",
  cursor: "pointer",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  fontSize: "16px",
  fontWeight: 500,
  lineHeight: "normal",
  margin: 0,
  outline: "none",
  padding: "16px 24px",
  textAlign: "center",
  textDecoration: "none",
  transition: "all 300ms cubic-bezier(0.23, 1, 0.32, 1)",
  userSelect: "none",
  WebkitUserSelect: "none",
  touchAction: "manipulation",
  height: "40px",
  willChange: "transform",
  "&:disabled": {
    pointerEvents: "none",
  },
  "&:hover": {
    color: "#057abe",
    backgroundColor: "#ffffff",
  },
  "&:active": {
    boxShadow: "none",
    transform: "translateY(0)",
  },
};
